In [681]:
#Import library
import torch
from torch import nn
import numpy as np
from torch.autograd import Variable
import pandas as pd

In [682]:
7200+55600+68600+47900

179300

# Create a Dataset

In [683]:
X1 = np.random.normal(0, 1, size=(100, 1)) 
X2 = np.random.normal(0, 1, size=(100, 1)) 
X3 = np.random.normal(0,1 , size=(100, 1)) 
Y = 1*X1+2*X2+4*X3+3 + np.random.normal(0,1 , size=(100, 1))
X = np.hstack((X1,X2, X3))
X_Train = Variable(torch.Tensor(X))
Y_Train = Variable(torch.Tensor(Y))

In [684]:
data = {"X1" : X1[:,0],"X2" : X2[:,0],"X3" : X3[:,0], "Y":Y[:,0]}
df = pd.DataFrame(data)  
df

X1        X2        X3          Y
0  -0.796653  0.261292  0.707335   6.246750
1  -0.012962  0.015452 -0.232989   1.496483
2   0.692559 -0.163414 -1.929627  -1.429067
3   0.367617 -0.252074  0.522062   5.764367
4  -0.141039 -0.686807 -0.892543  -2.969211
..       ...       ...       ...        ...
95 -1.702592 -0.196430  0.896199   4.547389
96  0.290724  0.319295 -0.887759  -1.776310
97 -0.848191  0.523350 -0.114807   3.020802
98 -0.782181 -1.282353 -2.565802 -11.334153
99  0.401314 -1.975148  0.064807  -0.466198

[100 rows x 4 columns]

In [685]:

X = torch.normal(0, 1, (1000, 3))
y = torch.matmul(X, torch.tensor([1.0, 2, 4])) + 3 + torch.normal(0, 1.0, torch.Size([1000]))/1000000
############
Y = y.reshape((-1, 1))
X_Train = X
Y_Train = Y
data = {"X1" : X.numpy()[:,0],"X2" : X.numpy()[:,1],"X3" : X.numpy()[:,2], "Y":y}
df = pd.DataFrame(data)  
df

X1        X2        X3         Y
0   -0.904996  1.601225 -1.160352  0.656045
1   -0.408843  0.557574  0.589575  6.064606
2    0.573054  0.939472  0.345655  6.834617
3   -1.081524  0.292687 -0.205934  1.680111
4   -0.427468  0.362836  1.505525  9.320303
..        ...       ...       ...       ...
995 -0.830238  0.831841  1.301149  9.038044
996  2.264081  0.148189 -1.074924  1.260763
997  1.999624  0.353115 -0.603923  3.290163
998  0.744615  1.324343 -0.352554  4.983086
999  0.454596  1.939948  0.498064  9.326749

[1000 rows x 4 columns]

In [686]:
X_Train  = torch.normal(0, 1, (1000, 3))
y = torch.matmul(X, torch.tensor([1.0, 2, 4])) + 3 + torch.normal(0, 1.0, torch.Size([1000]))/100000
############
Y_Train = y.reshape((-1, 1))

# Define the model

In [687]:
InputDim = 3
OutputDim = 1
class LinearRegression(torch.nn.Module):
    def __init__(self): 
        super(LinearRegression, self).__init__() 
        self.linear = torch.nn.Linear(InputDim, OutputDim)  
    def forward(self, x): 
        predict_y = self.linear(x) 
        return predict_y 
linear_model = LinearRegression()

# Define the Loss Function and an Optimization Algorithm

In [688]:
#define_criterion = torch.nn.MSELoss(size_average=False) replace with:
criterion = torch.nn.MSELoss( reduction='sum')
Optimizer = torch.optim.SGD(linear_model.parameters(), lr=0.000001)

In [689]:
for epoch in range(5000): 
    yhat = linear_model(X_Train)
    loss = criterion(yhat, Y_Train) 
    Optimizer.zero_grad() 
    loss.backward() 
    Optimizer.step() 
    print('epoch {}, loss function {}'.format(epoch, loss.item()))

epoch 0, loss function 29134.08203125
epoch 1, loss function 29108.859375
epoch 2, loss function 29083.73828125
epoch 3, loss function 29058.716796875
epoch 4, loss function 29033.794921875
epoch 5, loss function 29008.97265625
epoch 6, loss function 28984.248046875
epoch 7, loss function 28959.625
epoch 8, loss function 28935.095703125
epoch 9, loss function 28910.66796875
epoch 10, loss function 28886.33203125
epoch 11, loss function 28862.09765625
epoch 12, loss function 28837.958984375
epoch 13, loss function 28813.9140625
epoch 14, loss function 28789.96484375
epoch 15, loss function 28766.11328125
epoch 16, loss function 28742.357421875
epoch 17, loss function 28718.693359375
epoch 18, loss function 28695.125
epoch 19, loss function 28671.650390625
epoch 20, loss function 28648.271484375
epoch 21, loss function 28624.984375
epoch 22, loss function 28601.783203125
epoch 23, loss function 28578.6796875
epoch 24, loss function 28555.669921875
epoch 25, loss function 28532.75
epoch 2

epoch 505, loss function 23627.455078125
epoch 506, loss function 23624.03515625
epoch 507, loss function 23620.630859375
epoch 508, loss function 23617.240234375
epoch 509, loss function 23613.859375
epoch 510, loss function 23610.49609375
epoch 511, loss function 23607.140625
epoch 512, loss function 23603.802734375
epoch 513, loss function 23600.4765625
epoch 514, loss function 23597.1640625
epoch 515, loss function 23593.86328125
epoch 516, loss function 23590.576171875
epoch 517, loss function 23587.30078125
epoch 518, loss function 23584.0390625
epoch 519, loss function 23580.791015625
epoch 520, loss function 23577.5546875
epoch 521, loss function 23574.33203125
epoch 522, loss function 23571.12109375
epoch 523, loss function 23567.921875
epoch 524, loss function 23564.73828125
epoch 525, loss function 23561.564453125
epoch 526, loss function 23558.40234375
epoch 527, loss function 23555.255859375
epoch 528, loss function 23552.119140625
epoch 529, loss function 23548.99609375
e

epoch 1157, loss function 22819.0625
epoch 1158, loss function 22818.791015625
epoch 1159, loss function 22818.521484375
epoch 1160, loss function 22818.251953125
epoch 1161, loss function 22817.984375
epoch 1162, loss function 22817.716796875
epoch 1163, loss function 22817.44921875
epoch 1164, loss function 22817.185546875
epoch 1165, loss function 22816.921875
epoch 1166, loss function 22816.66015625
epoch 1167, loss function 22816.396484375
epoch 1168, loss function 22816.134765625
epoch 1169, loss function 22815.875
epoch 1170, loss function 22815.615234375
epoch 1171, loss function 22815.359375
epoch 1172, loss function 22815.099609375
epoch 1173, loss function 22814.845703125
epoch 1174, loss function 22814.587890625
epoch 1175, loss function 22814.3359375
epoch 1176, loss function 22814.08203125
epoch 1177, loss function 22813.830078125
epoch 1178, loss function 22813.578125
epoch 1179, loss function 22813.328125
epoch 1180, loss function 22813.080078125
epoch 1181, loss functi

epoch 1842, loss function 22753.24609375
epoch 1843, loss function 22753.2265625
epoch 1844, loss function 22753.208984375
epoch 1845, loss function 22753.1875
epoch 1846, loss function 22753.16796875
epoch 1847, loss function 22753.1484375
epoch 1848, loss function 22753.12890625
epoch 1849, loss function 22753.107421875
epoch 1850, loss function 22753.08984375
epoch 1851, loss function 22753.0703125
epoch 1852, loss function 22753.052734375
epoch 1853, loss function 22753.03125
epoch 1854, loss function 22753.013671875
epoch 1855, loss function 22752.994140625
epoch 1856, loss function 22752.974609375
epoch 1857, loss function 22752.955078125
epoch 1858, loss function 22752.9375
epoch 1859, loss function 22752.919921875
epoch 1860, loss function 22752.8984375
epoch 1861, loss function 22752.884765625
epoch 1862, loss function 22752.86328125
epoch 1863, loss function 22752.84375
epoch 1864, loss function 22752.828125
epoch 1865, loss function 22752.806640625
epoch 1866, loss function 

epoch 2524, loss function 22748.35546875
epoch 2525, loss function 22748.35546875
epoch 2526, loss function 22748.353515625
epoch 2527, loss function 22748.3515625
epoch 2528, loss function 22748.349609375
epoch 2529, loss function 22748.349609375
epoch 2530, loss function 22748.34765625
epoch 2531, loss function 22748.345703125
epoch 2532, loss function 22748.34375
epoch 2533, loss function 22748.341796875
epoch 2534, loss function 22748.341796875
epoch 2535, loss function 22748.337890625
epoch 2536, loss function 22748.337890625
epoch 2537, loss function 22748.3359375
epoch 2538, loss function 22748.337890625
epoch 2539, loss function 22748.333984375
epoch 2540, loss function 22748.33203125
epoch 2541, loss function 22748.33203125
epoch 2542, loss function 22748.330078125
epoch 2543, loss function 22748.328125
epoch 2544, loss function 22748.326171875
epoch 2545, loss function 22748.32421875
epoch 2546, loss function 22748.32421875
epoch 2547, loss function 22748.322265625
epoch 2548

epoch 3195, loss function 22747.974609375
epoch 3196, loss function 22747.974609375
epoch 3197, loss function 22747.974609375
epoch 3198, loss function 22747.974609375
epoch 3199, loss function 22747.9765625
epoch 3200, loss function 22747.974609375
epoch 3201, loss function 22747.974609375
epoch 3202, loss function 22747.974609375
epoch 3203, loss function 22747.974609375
epoch 3204, loss function 22747.974609375
epoch 3205, loss function 22747.974609375
epoch 3206, loss function 22747.974609375
epoch 3207, loss function 22747.97265625
epoch 3208, loss function 22747.974609375
epoch 3209, loss function 22747.97265625
epoch 3210, loss function 22747.97265625
epoch 3211, loss function 22747.974609375
epoch 3212, loss function 22747.97265625
epoch 3213, loss function 22747.97265625
epoch 3214, loss function 22747.97265625
epoch 3215, loss function 22747.970703125
epoch 3216, loss function 22747.97265625
epoch 3217, loss function 22747.97265625
epoch 3218, loss function 22747.970703125
ep

epoch 3837, loss function 22747.943359375
epoch 3838, loss function 22747.943359375
epoch 3839, loss function 22747.943359375
epoch 3840, loss function 22747.94140625
epoch 3841, loss function 22747.943359375
epoch 3842, loss function 22747.943359375
epoch 3843, loss function 22747.943359375
epoch 3844, loss function 22747.9453125
epoch 3845, loss function 22747.943359375
epoch 3846, loss function 22747.943359375
epoch 3847, loss function 22747.943359375
epoch 3848, loss function 22747.943359375
epoch 3849, loss function 22747.943359375
epoch 3850, loss function 22747.9453125
epoch 3851, loss function 22747.943359375
epoch 3852, loss function 22747.943359375
epoch 3853, loss function 22747.943359375
epoch 3854, loss function 22747.94140625
epoch 3855, loss function 22747.9453125
epoch 3856, loss function 22747.943359375
epoch 3857, loss function 22747.943359375
epoch 3858, loss function 22747.943359375
epoch 3859, loss function 22747.943359375
epoch 3860, loss function 22747.94140625
e

epoch 4518, loss function 22747.94140625
epoch 4519, loss function 22747.9375
epoch 4520, loss function 22747.94140625
epoch 4521, loss function 22747.939453125
epoch 4522, loss function 22747.939453125
epoch 4523, loss function 22747.939453125
epoch 4524, loss function 22747.939453125
epoch 4525, loss function 22747.939453125
epoch 4526, loss function 22747.94140625
epoch 4527, loss function 22747.939453125
epoch 4528, loss function 22747.939453125
epoch 4529, loss function 22747.94140625
epoch 4530, loss function 22747.943359375
epoch 4531, loss function 22747.943359375
epoch 4532, loss function 22747.943359375
epoch 4533, loss function 22747.94140625
epoch 4534, loss function 22747.939453125
epoch 4535, loss function 22747.94140625
epoch 4536, loss function 22747.94140625
epoch 4537, loss function 22747.939453125
epoch 4538, loss function 22747.94140625
epoch 4539, loss function 22747.94140625
epoch 4540, loss function 22747.939453125
epoch 4541, loss function 22747.94140625
epoch 4

In [544]:

test_variable = torch.randn(1, 3, requires_grad=True)

predict_y = linear_model()
predict_y

tensor([[1.0267]], grad_fn=<AddmmBackward0>)

In [632]:
X_Test  = torch.normal(0, 1, (1, 3))
y1 = torch.matmul(X_Test, torch.tensor([1.0, 2, 4])) + 3 + torch.normal(0, 1.0,torch.Size([1]))
Y_Test = y1.reshape((-1, 1))
yhat = linear_model(X_Test)
criterion(yhat, Y_Test)

tensor([[2.6843]], grad_fn=<AddmmBackward0>)

In [631]:
Y_Test

tensor([[1.5381]])

# Now I want to go deeper into this topic
* https://www.docker.com/blog/how-to-train-and-deploy-a-linear-regression-model-using-pytorch-part-1/

In [110]:
from torch.utils import data

In [573]:
num_examples = 1000
true_m = torch.tensor([2, -3.4, 8])
true_c = 4.2
X = torch.normal(0, 1, (num_examples, len(true_m)))
y = torch.matmul(X, true_m) + true_c
y += torch.normal(0, 0.01, y.shape)


In [552]:

y

tensor([ 1.5992e+01,  1.0520e+01,  1.6187e+01,  3.1880e-01, -3.0951e-01,
         5.9327e+00,  1.3813e+01, -4.3555e-01,  7.9810e+00,  9.8630e+00,
        -4.1379e+00,  9.9030e+00, -1.0143e+00, -2.8659e+00, -5.8441e+00,
         7.4970e+00,  1.0933e+00,  1.8477e+00, -7.8330e+00,  1.7300e+01,
         9.8987e+00,  7.7476e+00, -5.5060e+00,  1.7474e+00,  9.5069e+00,
        -1.1930e+00, -2.7354e+00, -7.6727e-01,  9.1535e+00,  1.1988e+01,
         2.7396e+00,  1.6699e+00,  7.9077e-01, -1.2517e+01,  1.7307e+01,
         2.1991e+01,  6.5792e+00, -2.5275e+00,  7.2011e+00, -3.5696e+00,
         1.0896e+01,  6.7077e+00, -1.6973e+01,  6.7691e+00,  1.4527e+01,
         1.4496e+01,  4.3423e+00, -5.6553e+00,  1.4569e+01,  2.7133e+00,
        -1.1959e+01,  2.6006e+00,  9.2810e+00, -9.9610e+00,  7.2776e+00,
         2.2769e+00, -6.0013e-01,  2.6475e+00, -7.9681e+00,  6.8091e+00,
         4.2370e+00,  9.6687e+00,  7.9880e+00,  1.2205e+01,  1.8572e+01,
         3.4821e-01,  5.5847e+00,  1.5187e+01, -1.5

In [553]:
labels = y.reshape((-1, 1))
labels

tensor([[ 1.5992e+01],
        [ 1.0520e+01],
        [ 1.6187e+01],
        [ 3.1880e-01],
        [-3.0951e-01],
        [ 5.9327e+00],
        [ 1.3813e+01],
        [-4.3555e-01],
        [ 7.9810e+00],
        [ 9.8630e+00],
        [-4.1379e+00],
        [ 9.9030e+00],
        [-1.0143e+00],
        [-2.8659e+00],
        [-5.8441e+00],
        [ 7.4970e+00],
        [ 1.0933e+00],
        [ 1.8477e+00],
        [-7.8330e+00],
        [ 1.7300e+01],
        [ 9.8987e+00],
        [ 7.7476e+00],
        [-5.5060e+00],
        [ 1.7474e+00],
        [ 9.5069e+00],
        [-1.1930e+00],
        [-2.7354e+00],
        [-7.6727e-01],
        [ 9.1535e+00],
        [ 1.1988e+01],
        [ 2.7396e+00],
        [ 1.6699e+00],
        [ 7.9077e-01],
        [-1.2517e+01],
        [ 1.7307e+01],
        [ 2.1991e+01],
        [ 6.5792e+00],
        [-2.5275e+00],
        [ 7.2011e+00],
        [-3.5696e+00],
        [ 1.0896e+01],
        [ 6.7077e+00],
        [-1.6973e+01],
        [ 6

In [114]:
batch_size = 10

In [115]:
data_arrays = (X, labels)

In [116]:
dataset = data.TensorDataset(*data_arrays)
dataset

In [117]:
data_iter = data.DataLoader(dataset, batch_size, shuffle=True)
data_iter

In [123]:
for X, y in data_iter:
    print(X,y)

tensor([[-0.4741,  0.0645, -0.2747],
        [ 1.1765,  0.0767,  0.7029],
        [-0.1647,  0.7800, -0.7397],
        [ 0.9177, -0.3356, -1.5822],
        [ 0.7624,  0.7372, -0.3704],
        [-0.4355,  0.0917, -1.1242],
        [ 1.8802, -0.6526,  0.3868],
        [ 1.1768, -1.3929,  0.1586],
        [-0.0452, -0.5718,  0.1165],
        [ 0.6459,  0.6444, -0.4780]]) tensor([[ 0.8407],
        [11.9224],
        [-4.6837],
        [-5.4909],
        [ 0.2721],
        [-5.9651],
        [13.2642],
        [12.5562],
        [ 6.9896],
        [-0.5261]])
tensor([[ 1.0635,  0.4535, -2.1084],
        [-0.8982,  1.2297, -0.2024],
        [ 0.2801,  0.2418, -0.3988],
        [-0.0743,  1.0724, -0.6607],
        [ 2.5289,  2.5730, -1.9285],
        [-1.3788, -0.1598,  0.0705],
        [ 1.2497,  1.1856, -0.5210],
        [-1.3608,  2.4439,  0.4963],
        [ 0.0881, -0.4497,  0.9120],
        [ 1.2733, -1.2467, -0.3691]]) tensor([[-12.0729],
        [ -3.3824],
        [  0.7515],
       

In [124]:
for X, y in data_iter:
    print(net(X),y)

tensor([[ 0.0150],
        [-0.0072],
        [-0.0017],
        [ 0.0181],
        [-0.0161],
        [ 0.0237],
        [-0.0078],
        [-0.0154],
        [ 0.0058],
        [-0.0037]], grad_fn=<AddmmBackward0>) tensor([[-0.3895],
        [ 8.0897],
        [-1.3057],
        [ 2.1030],
        [10.1771],
        [ 1.4505],
        [ 1.3295],
        [ 5.2976],
        [ 5.6724],
        [15.4548]])
tensor([[-0.0250],
        [-0.0084],
        [-0.0066],
        [ 0.0022],
        [ 0.0204],
        [-0.0006],
        [ 0.0040],
        [ 0.0150],
        [ 0.0020],
        [-0.0013]], grad_fn=<AddmmBackward0>) tensor([[  1.4944],
        [ -6.1937],
        [  3.5537],
        [ 11.1678],
        [ -5.6819],
        [  8.3619],
        [  8.1229],
        [-18.5283],
        [  4.3992],
        [  3.6172]])
tensor([[ 0.0029],
        [-0.0060],
        [-0.0235],
        [ 0.0039],
        [-0.0224],
        [-0.0015],
        [ 0.0015],
        [ 0.0168],
        [ 0.0085],
   

In [126]:
#Step4: Define model &amp;amp;amp; initialization
 
# Create a single layer feed-forward network with 2 inputs and 1 outputs.
 
net = nn.Linear(3, 1)
 

 
#Initialize model params
 
net.weight.data.normal_(0, 0.01)
 
net.bias.data.fill_(0)

tensor([0.])

In [120]:
loss = nn.MSELoss()

In [121]:
	
#Step 6: Define optimization algorithm
# implements a stochastic gradient descent optimization method
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

In [128]:
num_epochs = 5
 
for epoch in range(num_epochs):
 
    for X, y in data_iter:
 
        l = loss(net(X) ,y)
 
        trainer.zero_grad() #sets gradients to zero
 
    l.backward() # back propagation
 
    trainer.step() # parameter update
 
    l = loss(net(features), labels)
 
print(f'epoch {epoch + 1}, loss {l:f}')

NameError: name 'features' is not defined

# batch 
* https://deeplizard.com/learn/video/U4WB9p6ODjM
* https://www.analyticsvidhya.com/blog/2021/03/introduction-to-batch-normalization/
* https://www.baeldung.com/cs/epoch-vs-batch-vs-mini-batch
* https://machinelearningmastery.com/difference-between-a-batch-and-an-epoch/
* https://machinelearningmastery.com/gentle-introduction-mini-batch-gradient-descent-configure-batch-size/
* https://machinelearningmastery.com/early-stopping-to-avoid-overtraining-neural-network-models/
* https://towardsdatascience.com/gradient-descent-algorithm-and-its-variants-10f652806a3