In [1]:
#Import library
import torch
from torch import nn
import numpy as np
from torch.autograd import Variable
import pandas as pd

# Create a Dataset

In [3]:
X1 = np.random.normal(0, 1, size=(100, 1)) 
X2 = np.random.normal(0, 1, size=(100, 1)) 
X3 = np.random.normal(0,1 , size=(100, 1)) 
Y = 1*X1+2*X2+4*X3+3 + np.random.normal(0,1 , size=(100, 1))
X = np.hstack((X1,X2, X3))
X_Train = Variable(torch.Tensor(X))
Y_Train = Variable(torch.Tensor(Y))

In [4]:
data = {"X1" : X1[:,0],"X2" : X2[:,0],"X3" : X3[:,0], "Y":Y[:,0]}
df = pd.DataFrame(data)  
df

X1        X2        X3         Y
0   0.575049  1.462458 -0.438670  4.531069
1   0.343925 -0.589662  0.621959  3.995380
2  -0.473574 -0.087061 -0.832309 -1.202699
3   0.547790  1.213853  0.076693  7.167453
4  -1.122368 -0.921258 -0.731452 -2.644413
..       ...       ...       ...       ...
95 -0.827159 -0.240044  1.879741  8.732666
96  1.104205  1.783585  0.567293  8.361414
97  0.199489 -0.140796  1.674478  9.089247
98 -0.688404 -1.372876 -0.155236 -2.585457
99 -0.721709 -0.494141 -2.236710 -6.905832

[100 rows x 4 columns]

In [5]:

X = torch.normal(0, 1, (1000, 3))
y = torch.matmul(X, torch.tensor([1.0, 2, 4])) + 3 + torch.normal(0, 1.0, torch.Size([1000]))/1000000
############
Y = y.reshape((-1, 1))
X_Train = X
Y_Train = Y
data = {"X1" : X.numpy()[:,0],"X2" : X.numpy()[:,1],"X3" : X.numpy()[:,2], "Y":y}
df = pd.DataFrame(data)  
df

X1        X2        X3          Y
0   -2.154893 -0.220490  0.854107   3.820555
1   -1.719194 -0.213630  0.908401   4.487152
2    0.788780  0.658063 -0.548548   2.910713
3   -0.832647 -0.029061 -0.684627  -0.629276
4    0.488314  1.195539 -0.711891   3.031830
..        ...       ...       ...        ...
995  0.037158 -2.561116 -2.611551 -12.531276
996  1.569149  1.724678  0.254074   9.034802
997  2.353843 -1.341353 -0.168997   1.995149
998  0.200322 -0.515604  0.936444   5.914889
999 -0.059950  0.710705 -0.862388   0.911910

[1000 rows x 4 columns]

In [686]:
X_Train  = torch.normal(0, 1, (1000, 3))
y = torch.matmul(X, torch.tensor([1.0, 2, 4])) + 3 + torch.normal(0, 1.0, torch.Size([1000]))/100000
############
Y_Train = y.reshape((-1, 1))

# Define the model

In [6]:
InputDim = 3
OutputDim = 1
class LinearRegression(torch.nn.Module):
    def __init__(self): 
        super(LinearRegression, self).__init__() 
        self.linear = torch.nn.Linear(InputDim, OutputDim)  
    def forward(self, x): 
        y_hat = self.linear(x) 
        return y_hat 
linear_model = LinearRegression()

# Define the Loss Function and an Optimization Algorithm

In [7]:
#define_criterion = torch.nn.MSELoss(size_average=False) replace with:
criterion = torch.nn.MSELoss( reduction='sum')
Optimizer = torch.optim.SGD(linear_model.parameters(), lr=0.000001)

In [8]:
for epoch in range(5000): 
    yhat = linear_model(X_Train)
    loss = criterion(yhat, Y_Train) 
    Optimizer.zero_grad() 
    loss.backward() 
    Optimizer.step() 
    print('epoch {}, loss function {}'.format(epoch, loss.item()))

epoch 0, loss function 38140.2578125
epoch 1, loss function 37982.9921875
epoch 2, loss function 37826.375
epoch 3, loss function 37670.40234375
epoch 4, loss function 37515.078125
epoch 5, loss function 37360.39453125
epoch 6, loss function 37206.34765625
epoch 7, loss function 37052.93359375
epoch 8, loss function 36900.15625
epoch 9, loss function 36748.0078125
epoch 10, loss function 36596.48828125
epoch 11, loss function 36445.59375
epoch 12, loss function 36295.32421875
epoch 13, loss function 36145.66796875
epoch 14, loss function 35996.6328125
epoch 15, loss function 35848.21484375
epoch 16, loss function 35700.40625
epoch 17, loss function 35553.2109375
epoch 18, loss function 35406.62109375
epoch 19, loss function 35260.63671875
epoch 20, loss function 35115.25390625
epoch 21, loss function 34970.47265625
epoch 22, loss function 34826.28515625
epoch 23, loss function 34682.6953125
epoch 24, loss function 34539.69921875
epoch 25, loss function 34397.29296875
epoch 26, loss fun

epoch 654, loss function 2565.310791015625
epoch 655, loss function 2554.757080078125
epoch 656, loss function 2544.246337890625
epoch 657, loss function 2533.779052734375
epoch 658, loss function 2523.355712890625
epoch 659, loss function 2512.97509765625
epoch 660, loss function 2502.636962890625
epoch 661, loss function 2492.340576171875
epoch 662, loss function 2482.0869140625
epoch 663, loss function 2471.8759765625
epoch 664, loss function 2461.70703125
epoch 665, loss function 2451.580078125
epoch 666, loss function 2441.494873046875
epoch 667, loss function 2431.450927734375
epoch 668, loss function 2421.448486328125
epoch 669, loss function 2411.487548828125
epoch 670, loss function 2401.56640625
epoch 671, loss function 2391.686767578125
epoch 672, loss function 2381.847900390625
epoch 673, loss function 2372.049560546875
epoch 674, loss function 2362.291259765625
epoch 675, loss function 2352.5732421875
epoch 676, loss function 2342.8955078125
epoch 677, loss function 2333.2

epoch 1343, loss function 150.32594299316406
epoch 1344, loss function 149.70904541015625
epoch 1345, loss function 149.09471130371094
epoch 1346, loss function 148.48280334472656
epoch 1347, loss function 147.87347412109375
epoch 1348, loss function 147.26658630371094
epoch 1349, loss function 146.6621856689453
epoch 1350, loss function 146.06028747558594
epoch 1351, loss function 145.46084594726562
epoch 1352, loss function 144.86395263671875
epoch 1353, loss function 144.2693634033203
epoch 1354, loss function 143.6772918701172
epoch 1355, loss function 143.08761596679688
epoch 1356, loss function 142.50039672851562
epoch 1357, loss function 141.91554260253906
epoch 1358, loss function 141.3331298828125
epoch 1359, loss function 140.75315856933594
epoch 1360, loss function 140.1755828857422
epoch 1361, loss function 139.60037231445312
epoch 1362, loss function 139.02749633789062
epoch 1363, loss function 138.45697021484375
epoch 1364, loss function 137.88868713378906
epoch 1365, los

epoch 2034, loss function 8.796785354614258
epoch 2035, loss function 8.760796546936035
epoch 2036, loss function 8.724940299987793
epoch 2037, loss function 8.68923568725586
epoch 2038, loss function 8.653663635253906
epoch 2039, loss function 8.618233680725098
epoch 2040, loss function 8.582956314086914
epoch 2041, loss function 8.547812461853027
epoch 2042, loss function 8.512818336486816
epoch 2043, loss function 8.4779634475708
epoch 2044, loss function 8.443262100219727
epoch 2045, loss function 8.408711433410645
epoch 2046, loss function 8.374296188354492
epoch 2047, loss function 8.340015411376953
epoch 2048, loss function 8.305893898010254
epoch 2049, loss function 8.271893501281738
epoch 2050, loss function 8.238027572631836
epoch 2051, loss function 8.204309463500977
epoch 2052, loss function 8.1707124710083
epoch 2053, loss function 8.1372652053833
epoch 2054, loss function 8.1039457321167
epoch 2055, loss function 8.070762634277344
epoch 2056, loss function 8.0377254486083

epoch 2732, loss function 0.5036635994911194
epoch 2733, loss function 0.501606285572052
epoch 2734, loss function 0.4995603561401367
epoch 2735, loss function 0.49752160906791687
epoch 2736, loss function 0.49548599123954773
epoch 2737, loss function 0.4934607446193695
epoch 2738, loss function 0.4914475679397583
epoch 2739, loss function 0.4894402027130127
epoch 2740, loss function 0.48743876814842224
epoch 2741, loss function 0.4854463040828705
epoch 2742, loss function 0.48346760869026184
epoch 2743, loss function 0.4814893305301666
epoch 2744, loss function 0.47952204942703247
epoch 2745, loss function 0.4775623381137848
epoch 2746, loss function 0.47561246156692505
epoch 2747, loss function 0.4736710488796234
epoch 2748, loss function 0.4717331528663635
epoch 2749, loss function 0.46980559825897217
epoch 2750, loss function 0.4678896367549896
epoch 2751, loss function 0.4659789204597473
epoch 2752, loss function 0.4640708565711975
epoch 2753, loss function 0.4621734619140625
epoc

epoch 3445, loss function 0.027329452335834503
epoch 3446, loss function 0.027218762785196304
epoch 3447, loss function 0.027108732610940933
epoch 3448, loss function 0.02699819579720497
epoch 3449, loss function 0.026887811720371246
epoch 3450, loss function 0.026778321713209152
epoch 3451, loss function 0.02666907198727131
epoch 3452, loss function 0.02655928209424019
epoch 3453, loss function 0.026449793949723244
epoch 3454, loss function 0.02634107507765293
epoch 3455, loss function 0.026234213262796402
epoch 3456, loss function 0.02612772211432457
epoch 3457, loss function 0.026021042838692665
epoch 3458, loss function 0.02591453678905964
epoch 3459, loss function 0.025808967649936676
epoch 3460, loss function 0.02570553496479988
epoch 3461, loss function 0.025601647794246674
epoch 3462, loss function 0.025497809052467346
epoch 3463, loss function 0.025394724681973457
epoch 3464, loss function 0.025291677564382553
epoch 3465, loss function 0.025188785046339035
epoch 3466, loss fun

epoch 4084, loss function 0.002019776962697506
epoch 4085, loss function 0.0020115613006055355
epoch 4086, loss function 0.002003532601520419
epoch 4087, loss function 0.0019955274183303118
epoch 4088, loss function 0.0019873627461493015
epoch 4089, loss function 0.001979163382202387
epoch 4090, loss function 0.0019712040666490793
epoch 4091, loss function 0.0019631548784673214
epoch 4092, loss function 0.0019550444558262825
epoch 4093, loss function 0.0019470156403258443
epoch 4094, loss function 0.0019390934612601995
epoch 4095, loss function 0.0019311555661261082
epoch 4096, loss function 0.0019231290789321065
epoch 4097, loss function 0.0019156818743795156
epoch 4098, loss function 0.0019081924110651016
epoch 4099, loss function 0.0019007675582543015
epoch 4100, loss function 0.0018933683168143034
epoch 4101, loss function 0.0018859464908018708
epoch 4102, loss function 0.0018785424763336778
epoch 4103, loss function 0.001871237764135003
epoch 4104, loss function 0.0018637080211192

epoch 4652, loss function 0.00020391687576193362
epoch 4653, loss function 0.00020314710855018348
epoch 4654, loss function 0.00020235159900039434
epoch 4655, loss function 0.00020152170327492058
epoch 4656, loss function 0.00020069981110282242
epoch 4657, loss function 0.0001999241067096591
epoch 4658, loss function 0.00019914165022782981
epoch 4659, loss function 0.00019834170234389603
epoch 4660, loss function 0.00019749393686652184
epoch 4661, loss function 0.0001967305433936417
epoch 4662, loss function 0.00019596803758759052
epoch 4663, loss function 0.0001951659651240334
epoch 4664, loss function 0.00019434656132943928
epoch 4665, loss function 0.0001936055050464347
epoch 4666, loss function 0.00019280615379102528
epoch 4667, loss function 0.00019200460519641638
epoch 4668, loss function 0.00019120464276056737
epoch 4669, loss function 0.00019044053624384105
epoch 4670, loss function 0.00018968932272400707
epoch 4671, loss function 0.00018888518388848752
epoch 4672, loss functio

In [10]:

test_variable = torch.randn(1, 3, requires_grad=True)

predict_y = linear_model(test_variable)
predict_y

tensor([[-2.0533]], grad_fn=<AddmmBackward0>)

In [11]:
X_Test  = torch.normal(0, 1, (1, 3))
y1 = torch.matmul(X_Test, torch.tensor([1.0, 2, 4])) + 3 + torch.normal(0, 1.0,torch.Size([1]))
Y_Test = y1.reshape((-1, 1))
yhat = linear_model(X_Test)
criterion(yhat, Y_Test)

tensor(1.1103, grad_fn=<MseLossBackward0>)

In [631]:
Y_Test

tensor([[1.5381]])

# Now I want to go deeper into this topic
* https://www.docker.com/blog/how-to-train-and-deploy-a-linear-regression-model-using-pytorch-part-1/

In [110]:
from torch.utils import data

In [573]:
num_examples = 1000
true_m = torch.tensor([2, -3.4, 8])
true_c = 4.2
X = torch.normal(0, 1, (num_examples, len(true_m)))
y = torch.matmul(X, true_m) + true_c
y += torch.normal(0, 0.01, y.shape)


In [552]:

y

tensor([ 1.5992e+01,  1.0520e+01,  1.6187e+01,  3.1880e-01, -3.0951e-01,
         5.9327e+00,  1.3813e+01, -4.3555e-01,  7.9810e+00,  9.8630e+00,
        -4.1379e+00,  9.9030e+00, -1.0143e+00, -2.8659e+00, -5.8441e+00,
         7.4970e+00,  1.0933e+00,  1.8477e+00, -7.8330e+00,  1.7300e+01,
         9.8987e+00,  7.7476e+00, -5.5060e+00,  1.7474e+00,  9.5069e+00,
        -1.1930e+00, -2.7354e+00, -7.6727e-01,  9.1535e+00,  1.1988e+01,
         2.7396e+00,  1.6699e+00,  7.9077e-01, -1.2517e+01,  1.7307e+01,
         2.1991e+01,  6.5792e+00, -2.5275e+00,  7.2011e+00, -3.5696e+00,
         1.0896e+01,  6.7077e+00, -1.6973e+01,  6.7691e+00,  1.4527e+01,
         1.4496e+01,  4.3423e+00, -5.6553e+00,  1.4569e+01,  2.7133e+00,
        -1.1959e+01,  2.6006e+00,  9.2810e+00, -9.9610e+00,  7.2776e+00,
         2.2769e+00, -6.0013e-01,  2.6475e+00, -7.9681e+00,  6.8091e+00,
         4.2370e+00,  9.6687e+00,  7.9880e+00,  1.2205e+01,  1.8572e+01,
         3.4821e-01,  5.5847e+00,  1.5187e+01, -1.5

In [553]:
labels = y.reshape((-1, 1))
labels

tensor([[ 1.5992e+01],
        [ 1.0520e+01],
        [ 1.6187e+01],
        [ 3.1880e-01],
        [-3.0951e-01],
        [ 5.9327e+00],
        [ 1.3813e+01],
        [-4.3555e-01],
        [ 7.9810e+00],
        [ 9.8630e+00],
        [-4.1379e+00],
        [ 9.9030e+00],
        [-1.0143e+00],
        [-2.8659e+00],
        [-5.8441e+00],
        [ 7.4970e+00],
        [ 1.0933e+00],
        [ 1.8477e+00],
        [-7.8330e+00],
        [ 1.7300e+01],
        [ 9.8987e+00],
        [ 7.7476e+00],
        [-5.5060e+00],
        [ 1.7474e+00],
        [ 9.5069e+00],
        [-1.1930e+00],
        [-2.7354e+00],
        [-7.6727e-01],
        [ 9.1535e+00],
        [ 1.1988e+01],
        [ 2.7396e+00],
        [ 1.6699e+00],
        [ 7.9077e-01],
        [-1.2517e+01],
        [ 1.7307e+01],
        [ 2.1991e+01],
        [ 6.5792e+00],
        [-2.5275e+00],
        [ 7.2011e+00],
        [-3.5696e+00],
        [ 1.0896e+01],
        [ 6.7077e+00],
        [-1.6973e+01],
        [ 6

In [114]:
batch_size = 10

In [115]:
data_arrays = (X, labels)

In [116]:
dataset = data.TensorDataset(*data_arrays)
dataset

In [117]:
data_iter = data.DataLoader(dataset, batch_size, shuffle=True)
data_iter

In [123]:
for X, y in data_iter:
    print(X,y)

tensor([[-0.4741,  0.0645, -0.2747],
        [ 1.1765,  0.0767,  0.7029],
        [-0.1647,  0.7800, -0.7397],
        [ 0.9177, -0.3356, -1.5822],
        [ 0.7624,  0.7372, -0.3704],
        [-0.4355,  0.0917, -1.1242],
        [ 1.8802, -0.6526,  0.3868],
        [ 1.1768, -1.3929,  0.1586],
        [-0.0452, -0.5718,  0.1165],
        [ 0.6459,  0.6444, -0.4780]]) tensor([[ 0.8407],
        [11.9224],
        [-4.6837],
        [-5.4909],
        [ 0.2721],
        [-5.9651],
        [13.2642],
        [12.5562],
        [ 6.9896],
        [-0.5261]])
tensor([[ 1.0635,  0.4535, -2.1084],
        [-0.8982,  1.2297, -0.2024],
        [ 0.2801,  0.2418, -0.3988],
        [-0.0743,  1.0724, -0.6607],
        [ 2.5289,  2.5730, -1.9285],
        [-1.3788, -0.1598,  0.0705],
        [ 1.2497,  1.1856, -0.5210],
        [-1.3608,  2.4439,  0.4963],
        [ 0.0881, -0.4497,  0.9120],
        [ 1.2733, -1.2467, -0.3691]]) tensor([[-12.0729],
        [ -3.3824],
        [  0.7515],
       

In [124]:
for X, y in data_iter:
    print(net(X),y)

tensor([[ 0.0150],
        [-0.0072],
        [-0.0017],
        [ 0.0181],
        [-0.0161],
        [ 0.0237],
        [-0.0078],
        [-0.0154],
        [ 0.0058],
        [-0.0037]], grad_fn=<AddmmBackward0>) tensor([[-0.3895],
        [ 8.0897],
        [-1.3057],
        [ 2.1030],
        [10.1771],
        [ 1.4505],
        [ 1.3295],
        [ 5.2976],
        [ 5.6724],
        [15.4548]])
tensor([[-0.0250],
        [-0.0084],
        [-0.0066],
        [ 0.0022],
        [ 0.0204],
        [-0.0006],
        [ 0.0040],
        [ 0.0150],
        [ 0.0020],
        [-0.0013]], grad_fn=<AddmmBackward0>) tensor([[  1.4944],
        [ -6.1937],
        [  3.5537],
        [ 11.1678],
        [ -5.6819],
        [  8.3619],
        [  8.1229],
        [-18.5283],
        [  4.3992],
        [  3.6172]])
tensor([[ 0.0029],
        [-0.0060],
        [-0.0235],
        [ 0.0039],
        [-0.0224],
        [-0.0015],
        [ 0.0015],
        [ 0.0168],
        [ 0.0085],
   

In [126]:
#Step4: Define model &amp;amp;amp; initialization
 
# Create a single layer feed-forward network with 2 inputs and 1 outputs.
 
net = nn.Linear(3, 1)
 

 
#Initialize model params
 
net.weight.data.normal_(0, 0.01)
 
net.bias.data.fill_(0)

tensor([0.])

In [120]:
loss = nn.MSELoss()

In [121]:
	
#Step 6: Define optimization algorithm
# implements a stochastic gradient descent optimization method
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

In [128]:
num_epochs = 5
 
for epoch in range(num_epochs):
 
    for X, y in data_iter:
 
        l = loss(net(X) ,y)
 
        trainer.zero_grad() #sets gradients to zero
 
    l.backward() # back propagation
 
    trainer.step() # parameter update
 
    l = loss(net(features), labels)
 
print(f'epoch {epoch + 1}, loss {l:f}')

NameError: name 'features' is not defined

# batch 
* https://deeplizard.com/learn/video/U4WB9p6ODjM
* https://www.analyticsvidhya.com/blog/2021/03/introduction-to-batch-normalization/
* https://www.baeldung.com/cs/epoch-vs-batch-vs-mini-batch
* https://machinelearningmastery.com/difference-between-a-batch-and-an-epoch/
* https://machinelearningmastery.com/gentle-introduction-mini-batch-gradient-descent-configure-batch-size/
* https://machinelearningmastery.com/early-stopping-to-avoid-overtraining-neural-network-models/
* https://towardsdatascience.com/gradient-descent-algorithm-and-its-variants-10f652806a3